server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.243.83:8848
  data:
    redis:
      host: 172.20.243.83
      port: 6379